language: java
jdk:
- oraclejdk8

addons:
  ssh_known_hosts: neerc.ifmo.ru

before_deploy:
- openssl aes-256-cbc -K $encrypted_f2eee17a7175_key -iv $encrypted_f2eee17a7175_iv
  -in scripts/deploy_key.enc -out /tmp/deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_key
- ssh-add /tmp/deploy_key

deploy:
  provider: script
  skip_cleanup: true
  script: scripts/deploy.sh
  on:
    branch: master
