
@startuml

class Event {
    long id
    Year year
    String name
    String information
    Set<UserEvent> users
}

class Hall {
    long id
    String name
}

class Position {
    long id
    String name
}

class Role {
    long id
    String name
}

class User {
    long id
    String firstName
    String lastName
    String firstNameCyr
    String lastNameCyr
    String password
    String badgeName
    String badgeNameCyr
    String email
    Role role
}

class UserEvent {
    long id
    ApplicationForm
    userYear
    Event event
    Position position
    Hall hall
}

class ApplicationForm {
    long id
    User user
    Year year
    Set<Position> positions //желаемые позиции
    String suggestions
    String group
}

class Year {
    long id
    String name
    Set<ApplicationFrom> users
}

User --> Role : role
ApplicationForm "one" --> "many" Position : positions
ApplicationForm --> User : user
Year "one" --> "many" ApplicationForm : users

ApplicationForm --> Year : year

UserEvent --> ApplicationForm : userYear
UserEvent --> Hall : hall
UserEvent --> Position : position
UserEvent --> Event : event

Event "one" --> "many" UserEvent : users

@enduml