spring:
  profiles:
    active:
      - mysql
      - mail

  thymeleaf:
    prefix:  /WEB-INF/view/
    suffix: .html
    cache: false

  messages:
    encoding: UTF-8
    basename: messages/messages

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

server:
  context-path: /
