spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/volonteer
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialize: true
server:
  context-path: /volunteers


