spring:
  profiles:
    active:
      - mysql

  thymeleaf:
    prefix:  /WEB-INF/view/
    suffix: .html
    cache: false

  messages:
    basename: messages/messages
      
server:
  context-path: /
  