spring:
  profiles:
    active:
      - mysql
      - mail

  thymeleaf:
    prefix:  /WEB-INF/view/
    suffix: .html
    cache: false

  messages:
    encoding: UTF-8
    basename: messages/messages

      
server:
  context-path: /
  