spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3309/volunteers?useUnicode=true&characterEncoding=utf8
    username: volunteers
    password: Mat135qd
    driver-class-name: com.mysql.jdbc.Driver
    initialize: true
